version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    environment:
      REDIS_HOST: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: student_profiles_db
    ports:
      - "27020:27017"
      
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  app:
    build: .
    depends_on:
      - mysql
      - redis
      - mongodb
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
