apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_DB: student_db
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
