apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_USER: dXNlcg==  # Base64-encoded: user
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # Base64-encoded: password
  MYSQL_ROOT_PASSWORD: cm9vdA==  # Base64-encoded: root
