apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  MYSQL_DB: "{{ .Values.mysql.database }}"
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
