apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
